export default [
        {
            "id": 1,
            "firstName": "Alan",
            "lastName": "Andrusky",
            "portfolio": "https://www.canva.com/design/DAESeJGphvk/bpdB6WrILTYSAqqsCp2fTA/view?website#2",
            "github": "https://github.com/aandrusky",
            "linkedIn": "https://www.linkedin.com/in/alanandrusky/",
            "email": "alanandrusky@gmail.com",
            "proImg": "alan_pro.jpg",
            "funImg": "alan_fun.png",
            "isHired": false,
            "resume": "AlanAndrusky.pdf",
            "capstoneURL": "",
            "quote": "Example",
            "quoteAuthor": ""
        },
        {
            "id": 3,
            "firstName": "Will",
            "lastName": "Bishop",
            "portfolio": "https://www.willbishop.dev/",
            "github": "https://github.com/billwishop",
            "linkedIn": "https://www.linkedin.com/in/will-bishop-software-developer/",
            "email": "willbishop.hello@gmail.com",
            "proImg": "will_pro.JPG",
            "funImg": "will_fun.jpeg",
            "isHired": false,
            "resume": "WillBishop.pdf",
            "capstoneURL": "",
            "quote": "A much larger and robust, although marginally unnecessary (exept to show examplary exceptions); and possilby short enough to circumvent noticibility; however doubtful, example",
            "quoteAuthor": "-Baby Jesus"
        },
        {
            "id": 4,
            "firstName": "Jake",
            "lastName": "Butler",
            "portfolio": "https://jakebutlerwebdev.com/",
            "github": "https://www.github.com/TJakeButler",
            "linkedIn": "https://www.linkedin.com/in/jake-butler-web-dev/",
            "email": "tjakebutler@gmail.com",
            "proImg": "jake_pro.png",
            "funImg": "jake_fun.png",
            "isHired": false,
            "resume": "JakeButler.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 5,
            "firstName": "Charlie",
            "lastName": "Butterworth",
            "portfolio": "https://charliebutterworth.github.io/",
            "github": "https://github.com/CharlieButterworth",
            "linkedIn": "https://www.linkedin.com/in/cbutterworth3/",
            "email": "charlessbutterworth@gmail.com",
            "proImg": "charlie_pro.jpeg",
            "funImg": "charlie_fun.jpeg",
            "isHired": false,
            "resume": "CharlieButterworth.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 6,
            "firstName": "Mario",
            "lastName": "Campopiano",
            "portfolio": "https://mcampopiano.github.io/mario-campopiano-portfolio/",
            "github": "https://github.com/mcampopiano",
            "linkedIn": "https://www.linkedin.com/in/mcampopiano/",
            "email": "mcampopiano92@gmail.com",
            "proImg": "mario_pro.jpg",
            "funImg": "mario_fun.jpg",
            "isHired": false,
            "resume": "MarioCampopiano.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 7,
            "firstName": "Shawn",
            "lastName": "Conerton",
            "portfolio": "https://www.canva.com/design/DAESezY2obY/1lVoG7su6aJoc66iT1Lf_w/view?website#2",
            "github": "https://github.com/conerton",
            "linkedIn": "https://www.linkedin.com/in/shawnconerton/",
            "email": "conerton52@gmail.com",
            "proImg": "shawn_pro.png",
            "funImg": "shawn_fun.png",
            "isHired": false,
            "resume": "ShawnConerton.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 8,
            "firstName": "Dillon",
            "lastName": "Draper",
            "portfolio": "https://dillonbdraper.github.io/",
            "github": "https://www.github.com/DillonbDraper",
            "linkedIn": "https://www.linkedin.com/in/dillonbdraper",
            "email": "dillonbdraper@gmail.com",
            "proImg": "dillon_pro.jpg",
            "funImg": "dillon_fun.jpg",
            "isHired": false,   
            "resume": "DillonDraper.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 9,
            "firstName": "Jasmin",
            "lastName": "Kaset",
            "portfolio": "https://www.jasminkaset.net/",
            "github": "https://github.com/jkaset",
            "linkedIn": "https://www.linkedin.com/in/jkaset",
            "email": "jasminkaset@gmail.com",
            "proImg": "jasmin_pro.jpg",
            "funImg": "jasmin_fun.jpg",
            "isHired": false,
            "resume": "JasminKaset.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 10,
            "firstName": "Devin",
            "lastName": "Kent",
            "portfolio": "https://dalamcd.github.io/personal-site/",
            "github": "https://www.github.com/dalamcd",
            "linkedIn": "https://www.linkedin.com/in/devinkent",
            "email": "dalamcd@gmail.com",
            "proImg": "devin_pro.jpg",
            "funImg": "devin_fun.jfif",
            "isHired": false,
            "resume": "DevinKent.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 11,
            "firstName": "Jaron",
            "lastName": "Lane",
            "portfolio": "https://jaron-lane.github.io/",
            "github": "https://github.com/Jaron-Lane",
            "linkedIn": "https://www.linkedin.com/in/jaron-lane/",
            "email": "jaronwohlwend@icloud.com",
            "proImg": "jaron_pro.png",
            "funImg": "jaron_fun.png",
            "isHired": false,
            "resume": "JaronLane.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 12,
            "firstName": "Jayna",
            "lastName": "Leitze",
            "portfolio": "https://www.canva.com/design/DAESYyjW25w/zHGVxERWxY8K0v-LAiBXFg/view?website#2:jayna-leitze",
            "github": "https://github.com/JaynaLeitze",
            "linkedIn": "https://www.linkedin.com/in/jaynaleitze",
            "email": "jayna.leitze@gmail.com",
            "proImg": "jayna_pro.JPG",
            "funImg": "jayna_fun.jpg",
            "isHired": false,
            "resume": "JaynaLeitze.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 13,
            "firstName": "Heath",
            "lastName": "Lester",
            "portfolio": "https://heath-lester.github.io/",
            "github": "https://github.com/Heath-Lester",
            "linkedIn": "https://www.linkedin.com/in/halester/",
            "email": "h.allen.lester@gmail.com",
            "proImg": "heath_pro.JPG",
            "funImg": "heath_fun.jpg",
            "isHired": false,
            "resume": "HeathLester.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 14,
            "firstName": "Silas",
            "lastName": "Lowe",
            "portfolio": "https://www.silaslowe.net/",
            "github": "https://www.github.com/silaslowe",
            "linkedIn": "https://www.linkedin.com/in/silaslowe/",
            "email": "silaslowe@gmail.com",
            "proImg": "silas_pro.jpg",
            "funImg": "silas_fun.jpg",
            "isHired": false,
            "resume": "SilasLowe.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 15,
            "firstName": "Matthew",
            "lastName": "Machurek",
            "portfolio": "https://mrjm2005.wixsite.com/mysite",
            "github": "https://github.com/MatthewM1986",
            "linkedIn": "https://www.linkedin.com/in/matthew-machurek",
            "email": "mrjm2005@yahoo.com",
            "proImg": "matthew_pro.png",
            "funImg": "matthew_fun.JPG",
            "isHired": false,
            "resume": "MatthewMachurek.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 16,
            "firstName": "Ted",
            "lastName": "Marov",
            "portfolio": "https://tedmarov.github.io/",
            "github": "https://github.com/tedmarov",
            "linkedIn": "https://www.linkedin.com/in/tedmarov",
            "email": "tedmarov@gmail.com",
            "proImg": "ted_pro.jpg",
            "funImg": "ted_fun.jpg",
            "isHired": false,
            "resume": "TedMarov.pdf",
            "capstoneURL": "",
            "quote": "If you want to find out who someone is to the bottom, give them power. Anyone can stand adversity; only the great can stand prosperity.",
            "quoteAuthor": "- Robert G. Ingersoll"
        },
        {
            "id": 17,
            "firstName": "Danny",
            "lastName": "McCracken",
            "portfolio": "https://www.dannymccracken.dev/",
            "github": "https://www.github.com/dmccracken13",
            "linkedIn": "https://www.linkedin.com/in/danny-mccracken",
            "email": "dannymccracken13@gmail.com",
            "proImg": "danny_pro.JPG",
            "funImg": "danny_fun.jpg",
            "isHired": false,
            "resume": "DannyMcCracken.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 18,
            "firstName": "Travis",
            "lastName": "Milner",
            "portfolio": "https://travismilner.com/",
            "github": "https://github.com/TravisMilner",
            "linkedIn": "https://www.linkedin.com/in/travismilner1/",
            "email": "travismilner1@gmail.com",
            "proImg": "travisM_pro.png",
            "funImg": "travisM_fun.jpg",
            "isHired": false,
            "resume": "TravisMilner.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 19,
            "firstName": "Kyle",
            "lastName": "Nevels",
            "portfolio": "https://knevels1.github.io/",
            "github": "https://github.com/Knevels1",
            "linkedIn": "https://www.linkedin.com/in/kylenevels/",
            "email": "kyle.a.nevels@icloud.com",
            "proImg": "kyleN_pro.jpg",
            "funImg": "kyleN_fun.png",
            "isHired": true,
            "resume": "KyleNevels.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 20,
            "firstName": "Erica",
            "lastName": "Phillips",
            "portfolio": "https://ericaphillips.github.io/portfolio/",
            "github": "https://github.com/ericaphillips",
            "linkedIn": "https://www.linkedin.com/in/erica-phillips0/",
            "email": "ericaphill@gmail.com",
            "proImg": "erica_pro.jpg",
            "funImg": "erica_fun.JPG",
            "isHired": false,
            "resume": "EricaPhillips.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 21,
            "firstName": "Suganya",
            "lastName": "Prakash",
            "portfolio": "https://suganya-dev.github.io/",
            "github": "https://github.com/Suganya-dev",
            "linkedIn": "https://www.linkedin.com/in/suganyachandarraj/",
            "email": "suganprakash0621@gmail.com",
            "proImg": "suganya_pro.jpg",
            "funImg": "suganya_fun.png",
            "isHired": false,
            "resume": "SuganyaPrakash.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 22,
            "firstName": "Sanjeet",
            "lastName": "Prasad",
            "portfolio": "https://sanjeetprasad.github.io/portfolio/",
            "github": "https://github.com/sanjeetprasad",
            "linkedIn": "https://www.linkedin.com/in/sanjeetprasad/",
            "email": "sanjeet.l.prasad@gmail.com",
            "proImg": "sanjeet_pro.jpg",
            "funImg": "sanjeet_fun.jpg",
            "isHired": false,
            "resume": "SanjeetPrasad.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 23,
            "firstName": "Leo",
            "lastName": "Rondeau",
            "portfolio": "https://leorondeau.io/",
            "github": "https://github.com/leorondeau",
            "linkedIn": "https://www.linkedin.com/in/leo-rondeau/",
            "email": "leorondeau2020@gmail.com",
            "proImg": "leo_pro.jpg",
            "funImg": "leo_fun.jpg",
            "isHired": false,
            "resume": "LeoRondeau.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 24,
            "firstName": "Benjamin",
            "lastName": "Schweizer",
            "portfolio": "https://www.bschweiz.co/",
            "github": "https://github.com/bschweiz",
            "linkedIn": "https://www.linkedin.com/in/bschweiz/",
            "email": "contact@bschweiz.co",
            "proImg": "ben_pro.jpg",
            "funImg": "ben_fun.jpg",
            "isHired": false,
            "resume": "BenjaminSchweizer.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 25,
            "firstName": "Kyle",
            "lastName": "Simmons",
            "portfolio": "https://darrenkylesimmons.com",
            "github": "https://github.com/KyleSimmonsC44",
            "linkedIn": "https://www.linkedin.com/in/darren-kyle-simmons/",
            "email": "darrensimmons92@gmail.com",
            "proImg": "kyleS_pro.Jpg",
            "funImg": "kyleS_fun.jpg",
            "isHired": false,
            "resume": "KyleSimmons.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 26,
            "firstName": "Kristen",
            "lastName": "Steele",
            "portfolio": "https://www.krsteele.com/",
            "github": "https://github.com/krsteele",
            "linkedIn": "https://www.linkedin.com/in/kristenraesteele/",
            "email": "kristenraesteele@gmail.com",
            "proImg": "kristen_pro.jpeg",
            "funImg": "kristen_fun.jpg",
            "isHired": false,
            "resume": "KristenSteele.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 27,
            "firstName": "Travis",
            "lastName": "Stevenson",
            "portfolio": "https://my-portfolio-7280cd.webflow.io/",
            "github": "https://github.com/TheTechTravis",
            "linkedIn": "https://www.linkedin.com/in/thetechtravis/",
            "email": "thetechtravis@outlook.com",
            "proImg": "travisS_pro.jpg",
            "funImg": "travisS_fun.jpg",
            "isHired": true,
            "resume": "TravisStevenson.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 28,
            "firstName": "Patrick",
            "lastName": "Stewart",
            "portfolio": "https://notthatpatrickstewart.com/",
            "github": "https://github.com/NotThatPatrickStewart",
            "linkedIn": "https://www.linkedin.com/in/notthatpatrickstewart/",
            "email": "notthatpatrickstewart@gmail.com",
            "proImg": "patrick_pro.jpg",
            "funImg": "patrick_fun.png",
            "isHired": false,
            "resume": "NotThatPatrickStewart.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        },
        {
            "id": 29,
            "firstName": "Susan",
            "lastName": "Wiens",
            "portfolio": "https://swiens.github.io/",
            "github": "https://github.com/swiens",
            "linkedIn": "https://www.linkedin.com/in/susanmichellewiens/",
            "email": "susanmichellewiens@gmail.com",
            "proImg": "susan_pro.jpg",
            "funImg": "susan_fun.jpg",
            "isHired": false,
            "resume": "SusanWiens.pdf",
            "capstoneURL": "",
            "quote": "Can’t stop, won’t stop",
            "quoteAuthor": " -Miley Cyrus (Philosopher)"
        },
        {
            "id": 30,
            "firstName": "David",
            "lastName": "Williams",
            "portfolio": "https://dwilliams91.github.io/MyPersonalWebsite/",
            "github": "https://github.com/dwilliams91",
            "linkedIn": "https://www.linkedin.com/in/david-lavine-williams/",
            "email": "david.lav.williams@gmail.com",
            "proImg": "david_pro.jpg",
            "funImg": "david_fun.jpg",
            "isHired": false,
            "resume": "DavidWilliams.pdf",
            "capstoneURL": "",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon"
        }
]
