export default [
        {
            "id": 1,
            "firstName": "Alan",
            "lastName": "Andrusky",
            "portfolio": "https://www.canva.com/design/DAESeJGphvk/bpdB6WrILTYSAqqsCp2fTA/view?website#2",
            "github": "https://github.com/aandrusky",
            "linkedIn": "https://www.linkedin.com/in/alanandrusky/",
            "email": "alanandrusky@gmail.com",
            "quote": "",
            "quoteAuthor": "",
            "proImg": "alan_pro.jpg",
            "funImg": "alan_fun.png",
            "isHired": false,
            "resume": "AlanAndrusky.pdf",
            "capstoneURL": ""
        },
        {
            "id": 3,
            "firstName": "Will",
            "lastName": "Bishop",
            "portfolio": "https://www.willbishop.dev/",
            "github": "https://github.com/billwishop",
            "linkedIn": "https://www.linkedin.com/in/will-bishop-software-developer/",
            "email": "willbishop.hello@gmail.com",
            "quote": "“Hello, Newman.”",
            "quoteAuthor": "-Jerry Seinfeld",
            "proImg": "will_pro.JPG",
            "funImg": "will_fun.jpeg",
            "isHired": true,
            "resume": "WillBishop.pdf",
            "capstoneURL": "",
        },
        {
            "id": 4,
            "firstName": "Jake",
            "lastName": "Butler",
            "portfolio": "https://jakebutlerwebdev.com/",
            "github": "https://www.github.com/TJakeButler",
            "linkedIn": "https://www.linkedin.com/in/jake-butler-web-dev/",
            "email": "tjakebutler@gmail.com",
            "quote": "“You have to be interested to be interesting.”",
            "quoteAuthor": "",
            "proImg": "jake_pro.png",
            "funImg": "jake_fun.png",
            "isHired": true,
            "resume": "JakeButler.pdf",
            "capstoneURL": "",
        },
        {
            "id": 5,
            "firstName": "Charlie",
            "lastName": "Butterworth",
            "portfolio": "https://charliebutterworth.github.io/",
            "github": "https://github.com/CharlieButterworth",
            "linkedIn": "https://www.linkedin.com/in/cbutterworth3/",
            "email": "charlessbutterworth@gmail.com",
            "quote": "“In order to achieve growth, you have to pursue discomfort.”",
            "quoteAuthor": "-Chris Burkard",
            "proImg": "charlie_pro.jpeg",
            "funImg": "charlie_fun.jpeg",
            "isHired": false,
            "resume": "CharlieButterworth.pdf",
            "capstoneURL": "",
        },
        {
            "id": 6,
            "firstName": "Mario",
            "lastName": "Campopiano",
            "portfolio": "https://mcampopiano.github.io/mario-campopiano-portfolio/",
            "github": "https://github.com/mcampopiano",
            "linkedIn": "https://www.linkedin.com/in/mcampopiano/",
            "email": "mcampopiano92@gmail.com",
            "quote": "“Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying 'I will try again tomorrow.'”",
            "quoteAuthor": "-Mary Anne Radmacher",
            "proImg": "mario_pro.jpg",
            "funImg": "mario_fun.jpg",
            "isHired": true,
            "resume": "MarioCampopiano.pdf",
            "capstoneURL": ""
        },
        {
            "id": 7,
            "firstName": "Shawn",
            "lastName": "Conerton",
            "portfolio": "https://www.canva.com/design/DAESezY2obY/1lVoG7su6aJoc66iT1Lf_w/view?website#2",
            "github": "https://github.com/conerton",
            "linkedIn": "https://www.linkedin.com/in/shawnconerton/",
            "email": "conerton52@gmail.com",
            "quote": "“Efficiency by Shawn Conerton: I have been tasked to deliver a quote that is 149 characters long, so I will make sure to deliver that exact product.”",
            "quoteAuthor": "",
            "proImg": "shawn_pro.png",
            "funImg": "shawn_fun.png",
            "isHired": true,
            "resume": "ShawnConerton.pdf",
            "capstoneURL": ""
        },
        {
            "id": 8,
            "firstName": "Dillon",
            "lastName": "Draper",
            "portfolio": "https://dillonbdraper.github.io/",
            "github": "https://www.github.com/DillonbDraper",
            "linkedIn": "https://www.linkedin.com/in/dillonbdraper",
            "email": "dillonbdraper@gmail.com",
            "quote": "“There is no struggle too vast, no odds too overwhelming, for even should we fail- should we fall- we will know that we have lived.”",
            "quoteAuthor": "-Steven Erikson",
            "proImg": "dillon_pro.jpg",
            "funImg": "dillon_fun.jpg",
            "isHired": true,   
            "resume": "DillonDraper.pdf",
            "capstoneURL": ""
        },
        {
            "id": 9,
            "firstName": "Jasmin",
            "lastName": "Kaset",
            "portfolio": "https://www.jasminkaset.net/",
            "github": "https://github.com/jkaset",
            "linkedIn": "https://www.linkedin.com/in/jkaset",
            "quote": "“The way you make an omelet reveals your character.”",
            "quoteAuthor": "-Anthony Bourdain",
            "email": "jasminkaset@gmail.com",
            "proImg": "jasmin_pro.jpg",
            "funImg": "jasmin_fun.jpg",
            "isHired": true,
            "resume": "JasminKaset.pdf",
            "capstoneURL": ""
        },
        {
            "id": 10,
            "firstName": "Devin",
            "lastName": "Kent",
            "portfolio": "https://dalamcd.github.io/personal-site/",
            "github": "https://www.github.com/dalamcd",
            "linkedIn": "https://www.linkedin.com/in/devinkent",
            "email": "dalamcd@gmail.com",
            "quote": "",
            "quoteAuthor": "",
            "proImg": "devin_pro.jpg",
            "funImg": "devin_fun.jfif",
            "isHired": true,
            "resume": "DevinKent.pdf",
            "capstoneURL": ""
        },
        {
            "id": 11,
            "firstName": "Jaron",
            "lastName": "Lane",
            "portfolio": "https://jaron-lane.github.io/",
            "github": "https://github.com/Jaron-Lane",
            "linkedIn": "https://www.linkedin.com/in/jaron-lane/",
            "email": "jaronwohlwend@icloud.com",
            "quote": "“We’re all rough drafts of the people we’re still becoming.”",
            "quoteAuthor": "-Bob Goff",
            "proImg": "jaron_pro.png",
            "funImg": "jaron_fun.png",
            "isHired": false,
            "resume": "JaronLane.pdf",
            "capstoneURL": ""
        },
        {
            "id": 12,
            "firstName": "Jayna",
            "lastName": "Leitze",
            "portfolio": "https://www.canva.com/design/DAESYyjW25w/zHGVxERWxY8K0v-LAiBXFg/view?website#2:jayna-leitze",
            "github": "https://github.com/JaynaLeitze",
            "linkedIn": "https://www.linkedin.com/in/jaynaleitze",
            "email": "jayna.leitze@gmail.com",
            "quote": "“Anyways, you need people of intelligence on this sort of mission... quest... thing.”",
            "quoteAuthor": "-Peregrin Took",
            "proImg": "jayna_pro.JPG",
            "funImg": "jayna_fun.jpg",
            "isHired": false,
            "resume": "JaynaLeitze.pdf",
            "capstoneURL": ""
        },
        {
            "id": 13,
            "firstName": "Heath",
            "lastName": "Lester",
            "portfolio": "https://heath-lester.github.io/",
            "github": "https://github.com/Heath-Lester",
            "linkedIn": "https://www.linkedin.com/in/halester/",
            "quote": "“Seriousness is no more a guarantee of truth, insight, authenticity or probity, than humour is a guarantee of superficiality and stupidity.”",
            "quoteAuthor": "-Stephen Fry",
            "email": "h.allen.lester@gmail.com",
            "proImg": "heath_pro.JPG",
            "funImg": "heath_fun.jpg",
            "isHired": false,
            "resume": "HeathLester.pdf",
            "capstoneURL": ""
        },
        {
            "id": 14,
            "firstName": "Silas",
            "lastName": "Lowe",
            "portfolio": "https://www.silaslowe.net/",
            "github": "https://www.github.com/silaslowe",
            "linkedIn": "https://www.linkedin.com/in/silaslowe/",
            "email": "silaslowe@gmail.com",
            "quote": "“There are two ways to write error-free programs; only the third one works.”",
            "quoteAuthor": "-Alan Perlis, Epigrams in Programming",
            "proImg": "silas_pro.jpg",
            "funImg": "silas_fun.jpg",
            "isHired": false,
            "resume": "SilasLowe.pdf",
            "capstoneURL": ""
        },
        {
            "id": 15,
            "firstName": "Matthew",
            "lastName": "Machurek",
            "portfolio": "https://mrjm2005.wixsite.com/mysite",
            "github": "https://github.com/MatthewM1986",
            "linkedIn": "https://www.linkedin.com/in/matthew-machurek",
            "email": "mrjm2005@yahoo.com",
            "quote": "“It’s not what you achieve, it’s what you overcome. That’s what defines your career.” -Carlton Fisk",
            "quoteAuthor": "“If at first you don’t succeed; call it version 1.0”",
            "proImg": "matthew_pro.png",
            "funImg": "matthew_fun.JPG",
            "isHired": false,
            "resume": "MatthewMachurek.pdf",
            "capstoneURL": ""
        },
        {
            "id": 16,
            "firstName": "Ted",
            "lastName": "Marov",
            "portfolio": "https://tedmarov.github.io/",
            "github": "https://github.com/tedmarov",
            "linkedIn": "https://www.linkedin.com/in/tedmarov",
            "email": "tedmarov@gmail.com",
            "quote": "“If you want to find out who someone is to the bottom, give them power. Anyone can stand adversity, only the great can stand prosperity.”",
            "quoteAuthor": "-Robert G. Ingersoll",
            "proImg": "ted_pro.jpg",
            "funImg": "ted_fun.jpg",
            "isHired": false,
            "resume": "TedMarov.pdf",
            "capstoneURL": "",
        },
        {
            "id": 17,
            "firstName": "Danny",
            "lastName": "McCracken",
            "portfolio": "https://www.dannymccracken.dev/",
            "github": "https://www.github.com/dmccracken13",
            "linkedIn": "https://www.linkedin.com/in/danny-mccracken",
            "email": "dannymccracken13@gmail.com",
            "quote": "“This is the real secret of life, to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.”",
            "quoteAuthor": "-Alan Watts",
            "proImg": "danny_pro.JPG",
            "funImg": "danny_fun.jpg",
            "isHired": true,
            "resume": "DannyMcCracken.pdf",
            "capstoneURL": ""
        },
        {
            "id": 18,
            "firstName": "Travis",
            "lastName": "Milner",
            "portfolio": "https://travismilner.com/",
            "github": "https://github.com/TravisMilner",
            "linkedIn": "https://www.linkedin.com/in/travismilner1/",
            "email": "travismilner1@gmail.com",
            "quote": "“Tell me and I forget. Teach me and I remember. Involve me and I learn.”",
            "quoteAuthor": "-Benjamin Franklin",
            "proImg": "travisM_pro.png",
            "funImg": "travisM_fun.jpg",
            "isHired": true,
            "resume": "TravisMilner.pdf",
            "capstoneURL": ""
        },
        {
            "id": 19,
            "firstName": "Kyle",
            "lastName": "Nevels",
            "portfolio": "https://knevels1.github.io/",
            "github": "https://github.com/Knevels1",
            "linkedIn": "https://www.linkedin.com/in/kylenevels/",
            "email": "kyle.a.nevels@icloud.com",
            "quote": "“Set goals, stay focused, and go big or go home”",
            "proImg": "kyleN_pro.jpg",
            "funImg": "kyleN_fun.png",
            "isHired": true,
            "resume": "KyleNevels.pdf",
            "capstoneURL": ""
        },
        {
            "id": 20,
            "firstName": "Erica",
            "lastName": "Phillips",
            "portfolio": "https://ericaphillips.github.io/portfolio/",
            "github": "https://github.com/ericaphillips",
            "linkedIn": "https://www.linkedin.com/in/erica-phillips0/",
            "email": "ericaphill@gmail.com",
            "quote": "",
            "quoteAuthor": "",
            "proImg": "erica_pro.jpg",
            "funImg": "erica_fun.JPG",
            "isHired": false,
            "resume": "EricaPhillips.pdf",
            "capstoneURL": ""
        },
        {
            "id": 21,
            "firstName": "Suganya",
            "lastName": "Prakash",
            "portfolio": "https://suganya-dev.github.io/",
            "github": "https://github.com/Suganya-dev",
            "linkedIn": "https://www.linkedin.com/in/suganyachandarraj/",
            "email": "suganprakash0621@gmail.com",
            "quote": "“Difficult roads lead to beautiful destinations.”",
            "quoteAuthor": "",
            "proImg": "suganya_pro.jpg",
            "funImg": "suganya_fun.png",
            "isHired": false,
            "resume": "SuganyaPrakash.pdf",
            "capstoneURL": ""
        },
        {
            "id": 22,
            "firstName": "Sanjeet",
            "lastName": "Prasad",
            "portfolio": "https://sanjeetprasad.github.io/portfolio/",
            "github": "https://github.com/sanjeetprasad",
            "linkedIn": "https://www.linkedin.com/in/sanjeetprasad/",
            "email": "snnjeet.l.prasad@gmail.com",
            "quote": "“Arise, awake, and stop not till the goal is reached.”",
            "quoteAuthor": "-Swami Vivekananda",
            "proImg": "sanjeet_pro.jpg",
            "funImg": "sanjeet_fun.jpg",
            "isHired": true,
            "resume": "SanjeetPrasad.pdf",
            "capstoneURL": ""
        },
        {
            "id": 23,
            "firstName": "Leo",
            "lastName": "Rondeau",
            "portfolio": "https://leorondeau.io/",
            "github": "https://github.com/leorondeau",
            "linkedIn": "https://www.linkedin.com/in/leo-rondeau/",
            "email": "leorondeau2020@gmail.com",
            "quote": "“Somewhere, something incredible is waiting to be known.”",
            "quoteAuthor": "-Carl Sagan",
            "proImg": "leo_pro.jpg",
            "funImg": "leo_fun.jpg",
            "isHired": false,
            "resume": "LeoRondeau.pdf",
            "capstoneURL": ""
        },
        {
            "id": 24,
            "firstName": "Benjamin",
            "lastName": "Schweizer",
            "portfolio": "https://www.bschweiz.co/",
            "github": "https://github.com/bschweiz",
            "linkedIn": "https://www.linkedin.com/in/bschweiz/",
            "email": "contact@bschweiz.co",
            "quote": "“A day without sunshine is like, you know, night.”",
            "quoteAuthor": "-Steve Martin",
            "proImg": "ben_pro.jpg",
            "funImg": "ben_fun.jpg",
            "isHired": true,
            "resume": "BenjaminSchweizer.pdf",
            "capstoneURL": ""
        },
        {
            "id": 25,
            "firstName": "Kyle",
            "lastName": "Simmons",
            "portfolio": "https://darrenkylesimmons.com",
            "github": "https://github.com/KyleSimmonsC44",
            "linkedIn": "https://www.linkedin.com/in/darren-kyle-simmons/",
            "email": "darrensimmons92@gmail.com",
            "quote": "“Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.”",
            "quoteAuthor": "-Rick Osborne",
            "proImg": "kyleS_pro.Jpg",
            "funImg": "kyleS_fun.jpg",
            "isHired": true,
            "resume": "KyleSimmons.pdf",
            "capstoneURL": ""
        },
        {
            "id": 26,
            "firstName": "Kristen",
            "lastName": "Steele",
            "portfolio": "https://www.krsteele.com/",
            "github": "https://github.com/krsteele",
            "linkedIn": "https://www.linkedin.com/in/kristenraesteele/",
            "email": "kristenraesteele@gmail.com",
            "quote": "“Oh, you should never, never doubt what nobody is sure about.”",
            "quoteAuthor": "-Willy Wonka",
            "proImg": "kristen_pro.jpeg",
            "funImg": "kristen_fun.jpg",
            "isHired": true,
            "resume": "KristenSteele.pdf",
            "capstoneURL": ""
        },
        {
            "id": 27,
            "firstName": "Travis",
            "lastName": "Stevenson",
            "portfolio": "https://my-portfolio-7280cd.webflow.io/",
            "github": "https://github.com/TheTechTravis",
            "linkedIn": "https://www.linkedin.com/in/thetechtravis/",
            "email": "thetechtravis@outlook.com",
            "quote": "“The best thing about a boolean is even if you are wrong, you are only off by a bit.”",
            "quoteAuthor": "",
            "proImg": "travisS_pro.jpg",
            "funImg": "travisS_fun.jpg",
            "isHired": true,
            "resume": "TravisStevenson.pdf",
            "capstoneURL": ""
        },
        {
            "id": 28,
            "firstName": "Patrick",
            "lastName": "Stewart",
            "github": "https://github.com/NotThatPatrickStewart",
            "linkedIn": "https://www.linkedin.com/in/notthatpatrickstewart/",
            "portfolio": "https://notthatpatrickstewart.com/",
            "email": "notthatpatrickstewart@gmail.com",
            "quote": "“In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.”",
            "quoteAuthor": "-Douglas Adams",
            "proImg": "patrick_pro.jpg",
            "funImg": "patrick_fun.png",
            "isHired": false,
            "resume": "NotThatPatrickStewart.pdf",
            "capstoneURL": ""
        },
        {
            "id": 29,
            "firstName": "Susan",
            "lastName": "Wiens",
            "portfolio": "https://swiens.github.io/",
            "github": "https://github.com/swiens",
            "linkedIn": "https://www.linkedin.com/in/susanmichellewiens/",
            "email": "susanmichellewiens@gmail.com",
            "quote": "“Can’t stop, won’t stop.”",
            "quoteAuthor": " -Miley Cyrus (Philosopher)",
            "proImg": "susan_pro.jpg",
            "funImg": "susan_fun.jpg",
            "isHired": true,
            "resume": "SusanWiens.pdf",
            "capstoneURL": "",
        },
        {
            "id": 30,
            "firstName": "David",
            "lastName": "Williams",
            "portfolio": "https://dwilliams91.github.io/MyPersonalWebsite/",
            "github": "https://github.com/dwilliams91",
            "linkedIn": "https://www.linkedin.com/in/david-lavine-williams/",
            "email": "david.lav.williams@gmail.com",
            "quote": "",
            "quoteAuthor": "",
            "proImg": "david_pro.jpg",
            "funImg": "david_fun.jpg",
            "isHired": true,
            "resume": "DavidWilliams.pdf",
            "capstoneURL": ""
        }
]
