export default [
        {
            "id": 1,
            "firstName": "Alan",
            "lastName": "Andrusky",
            "quote": "Example",
            "quoteAuthor": "",
            "github": "https://github.com/Belljeremiah",
            "linkedIn": "https://www.linkedin.com/in/belljeremiah/",
            "portfolio": "",
            "email": "jeremiah.bell812.topper@gmail.com",
            "proImg": "jeremiah_serious.png",
            "funImg": "jeremiah_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "stAIvRPedSw"
        },
        {
            "id": 2,
            "firstName": "David",
            "lastName": "Bing",
            "quote": "Another Example",
            "quoteAuthor": "-Marcus Aurelius",
            "github": "https://github.com/rdbishop19",
            "linkedIn": "https://www.linkedin.com/in/ryandanielbishop/",
            "portfolio": "https://rdbishop19.github.io/",
            "email": "rdbishop06@gmail.com",
            "proImg": "ryan_bishop_serious.png",
            "funImg": "ryan_bishop_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "stAIvRPedSw"
        },
        {
            "id": 3,
            "firstName": "Will",
            "lastName": "Bishop",
            "quote": "A much larger and robust, although marginally unnecessary (exept to show examplary exceptions); and possilby short enough to circumvent noticibility; however doubtful, example",
            "quoteAuthor": "-Baby Jesus",
            "email": "cassandra.bacon@gmail.com",
            "github": "https://github.com/CassieBoyd",
            "linkedIn": "https://www.linkedin.com/in/cassandra-boyd/",
            "portfolio": "https://cassieboyd.github.io/",
            "proImg": "cassandra_serious.png",
            "funImg": "cassandra_fun.png",
            "isHired": false,
            "resume": "CassieBoyd-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 4,
            "firstName": "Jake",
            "lastName": "Butler",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "cassandra_serious.png",
            "funImg": "cassandra_fun.png",
            "isHired": false,
            "resume": "CassieBoyd-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 5,
            "firstName": "Charlie",
            "lastName": "Butterworth",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "kenneth_serious.png",
            "funImg": "kenneth_fun.png",
            "isHired": false,
            "resume": "KenBoyd-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 6,
            "firstName": "Mario",
            "lastName": "Campopiano",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "caroline_serious.png",
            "funImg": "caroline_serious.png",
            "isHired": false,
            "resume": "CarolineBrownlee-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 7,
            "firstName": "Shawn",
            "lastName": "Conerton",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIOhttps://manilabui.com/",
            "proImg": "manila_serious.png",
            "funImg": "manila_fun.png",
            "isHired": false,
            "resume": "ManilaBui-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 8,
            "firstName": "Dillon",
            "lastName": "Draper",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIOhttps://ajbyrd.github.io/GITHUBadambyrd/",
            "proImg": "adam_serious.png",
            "funImg": "adam_fun.png",
            "isHired": false,
            "resume": "AdamByrd-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 9,
            "firstName": "Jasmin",
            "lastName": "Kaset",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIOhttps://chapmanjamesg.github.io/GITHUB",
            "proImg": "james_serious.png",
            "funImg": "james_fun.png",
            "isHired": false,
            "resume": "JamesChapman-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 10,
            "firstName": "Devin",
            "lastName": "Kent",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "shawna_serious.png",
            "funImg": "shawna_fun.png",
            "isHired": false,
            "resume": "ShawnaChatfield-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 11,
            "firstName": "Jayna",
            "lastName": "Leitze",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIOhttps://www.cherkesky.com",
            "proImg": "guy_serious.png",
            "funImg": "guy_fun.png",
            "isHired": false,
            "resume": "GuyCherkesky-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 12,
            "firstName": "Heath",
            "lastName": "Lester",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIOhttps://ryancrowleycode.github.io/GITHUB",
            "proImg": "ryan_crowley_serious.png",
            "funImg": "ryan_crowley_fun.png",
            "isHired": false,
            "resume": "GuyCherkesky-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 13,
            "firstName": "Silas",
            "lastName": "Lowe",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIOhttps://rhc822.github.io/GITHUB",
            "proImg": "ryan_cunningham_serious.png",
            "funImg": "ryan_cunningham_serious.png",
            "isHired": false,
            "resume": "RyanCunningham-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 14,
            "firstName": "Matthew",
            "lastName": "Machurek",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIOhttps://chase-fite.github.io/GITHUB",
            "proImg": "chase_serious.png",
            "funImg": "chase_serious.png",
            "isHired": false,
            "resume": "ChaseFite-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
          },
        {
            "id": 15,
            "firstName": "Ted",
            "lastName": "Marov",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "julian_serious.png",
            "funImg": "julian_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 16,
            "firstName": "Danny",
            "lastName": "McCracken",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "corri_serious.png",
            "funImg": "corri_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 17,
            "firstName": "Travis",
            "lastName": "Milner",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "sophia_serious.png",
            "funImg": "sophia_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 18,
            "firstName": "Kyle",
            "lastName": "Nevels",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "charles_serious.png",
            "funImg": "charles_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 19,
            "firstName": "Erica",
            "lastName": "Phillips",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "michelle_serious.png",
            "funImg": "michelle_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 20,
            "firstName": "Suganya",
            "lastName": "Prakash",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "john_serious.png",
            "funImg": "john_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 21,
            "firstName": "Sanjeet",
            "lastName": "Prasad",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "jesie_serious.png",
            "funImg": "jesie_serious.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 22,
            "firstName": "Leo",
            "lastName": "Rondeau",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "sullivan_serious.png",
            "funImg": "sullivan_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 23,
            "firstName": "Benjamin",
            "lastName": "Schweizer",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "christian_serious.png",
            "funImg": "christian_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 24,
            "firstName": "Kyle",
            "lastName": "Simmons",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "sam_serious.png",
            "funImg": "sam_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 25,
            "firstName": "Kristen",
            "lastName": "Steele",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "erin_serious.png",
            "funImg": "erin_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 26,
            "firstName": "Travis",
            "lastName": "Stevenson",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "lauren_serious.png",
            "funImg": "lauren_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 27,
            "firstName": "Patrick",
            "lastName": "Stewart",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "melody_serious.png",
            "funImg": "melody_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 28,
            "firstName": "Susan",
            "lastName": "Wiens",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "trey_serious.png",
            "funImg": "trey_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 29,
            "firstName": "David",
            "lastName": "Williams",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "joseph_serious.png",
            "funImg": "joseph_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        },
        {
            "id": 30,
            "firstName": "Jaron",
            "lastName": "Wohlwend",
            "quote": "Here's a clever quote",
            "quoteAuthor": "-Anon",
            "email": "EMAIL",
            "github": "GITHUB",
            "linkedIn": "LINKEDIN",
            "portfolio": "PORTFOLIO",
            "proImg": "joseph_serious.png",
            "funImg": "joseph_fun.png",
            "isHired": false,
            "resume": "JeremiahBell-resume.pdf",
            "capstoneURL": "FUzktf9HPI4"
        }
]
